### ISSUE TITLE
Navigate to an url when clicking on a web push notification

### ISSUE THREAD

**Issue by sau-lanvy** [flauc/ng-push#13]
I'm trying to navigate to an url when clicking on the push notification, the template is rendering very slowly.

**Comment by sau-lanvy** [comment]
If i use the code as:
<pre>
<code>if (res.event.type === 'click') { this.router.navigate(['payment']);  }</code>
</pre>

Angular is silently break (looks like it is redirect but not reloading). Component's constructor is called but ngOnInit method isn't.

Instead, I'm using `run` of Angular zone to resolve the problem as below:
<pre>
<code>
if (res.event.type === 'click') {
    this.ngZone.run(() => {
       this.router.navigate(['payment']);
    });
}
</code>
</pre>

**Comment by flauc** [comment]
Awesome, thank you for sharing that @sau-lanvy 👍
