### ISSUE TITLE
Push not working after ng-build

### ISSUE THREAD

**Issue by SunilRumbaLama** [flauc/ng-push#17]
Hi! The ng-push after built and deployed doesnot ask for permission. And when i send in the push, it shows that the user has not granted permission for push.

Its working on localhost though. Great job with the plugin.

**Comment by Stajor** [comment]
@SunilRumbaLama 
Check console messages. In chrome I see the message when using http
```
[Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
```

**Comment by SunilRumbaLama** [comment]
@Stajor  thanks i was already into it
