### ISSUE TITLE
Please add @NgModule annotation

### ISSUE THREAD

**Issue by areijngoudt** [flauc/ng-push#2]
When I import the module in this way:

```
import { PushNotificationsModule } from 'ng-push';
...
@NgModule({
    imports: [
        ...
        PushNotificationsModule,
        ...
````

I get this runtime error

```
Uncaught Error: Unexpected value 'PushNotificationsModule' imported by the module 'SharedModule'. Please add a @NgModule annotation.
```

I've upgraded to angular 5.0.0 and now try to use ng-push instead of angular2-notifications.

**Comment by flauc** [comment]
Hi @areijngoudt,

Thank you for pointing this out 👍  
I will look into it later today, asap basically.

**Comment by flauc** [comment]
I can't recreate your issue. What setup are you using? Can you please try to create a basic plunkr with the issue?

**Comment by areijngoudt** [comment]
I solved it by importing the PushNotificationsService directly and added it to the providers collection of my own shared module. So for now my problem is solved. 
Thanks.

**Comment by flauc** [comment]
I'm happy to hear it 👍

**Comment by cdupetit** [comment]
This fix don't solve the problem of the module declaration.
