### ISSUE TITLE
Support for angular 4.x.x

### ISSUE THREAD

**Issue by danielavilam** [flauc/ng-push#3]
## **This is a...**

- [x]  feature request
- [ ] bug report
- [ ] usage question

## **Additional Notes:**

Currently this project does not support Angular 4.x.

What do we need to change to implement the support?

**Comment by flauc** [comment]
Hi @danielavilam1995,

No, I'm sorry, this project only supports 5.x.x. If you need 4.x.x support. Please look at an older version of this library. 

https://github.com/flauc/angular2-notifications

They used to be the same library.
I think a 0.7.x version should work nicely for you.
