### ISSUE TITLE
how to click to the notification

### ISSUE THREAD

**Issue by OdaiTu** [flauc/ng-push#4]
thank you
i want when click to notification to open a new window
i did this code but is doesnt work

`let opiotns= {
                    body: res.data[0].title,
                    icon: this.imgUrl + '100x100/' + res.data[0].image,
                    timeOut: 5000,
                    showProgressBar: true,
                    clickToClose: true,
                    preventLastDuplicates: true

                }
                this._pushNotifications.create('',opiotns).subscribe(
                   res.onclick = window.open(this.siteUrl + 'news/' + res.data[0].id)
                );`

**Comment by anode7** [comment]
Hi @OdaiTu 
a functional example with this version
```
   this.push.create('Test', { body: 'Ici il y a du nouveau !!', icon:"android-chrome-192x192.png"}).subscribe(
        res => {
          if(res.event.type=="click"){
            res.notification.close();
            window.open(this.siteUrl + 'news/' + res.data[0].id)
          }
        },
        err => console.log(err)
      )
```

**Comment by flauc** [comment]
@anode7 
thank you so much for jumping in on this one, I will add this to the documentation as well this weekend 👍

**Comment by OdaiTu** [comment]
solved now 
thanks
