### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by anode7** [flauc/ng-push#5]
When I install this script in a server/client environment, I have this error:
ReferenceError: the window is not defined

I solved it so far, like this:
To make co-exist with the SSR by importing the module in my browser-app. module. ts and not in the app. module. ts
├── app
│ ├── app.component.ts
│ ├── app.browser.module.ts
│ └── app.server.modue.ts
.......
├── index.html
├── main.browser.ts
└── main.server.ts

And in my component:
```
import { Component, OnInit, OnDestroy, Inject, PLATFORM_ID, Injector } from '@angular/core';
import {isPlatformBrowser } from '@angular/common';
...
@Component({ ...
})
export class HomeView implements OnInit, OnDestroy {
...
private _push:PushNotificationsService;
constructor(
    @Inject(PLATFORM_ID) platformId: string,
    private injector: Injector,
...
) {
    this.testBrowser = isPlatformBrowser(platformId);//Boolean
    if (this.testBrowser)this._push=this.injector.get(PushNotificationsService);//inject service only on browser platform
}
```
and it works well

**Comment by flauc** [comment]
Hi @anode7,

This library can't work in a server environment because the Notification API is a Web API 
https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by anode7** [comment]
I agree with that, but since Universal was integrated in Angular, it is very common to use SSR in projects. Especially when we talk about Angular 5.
If detection were used in your Service, it would be easier to use.

**Comment by flauc** [comment]
Actually, I disagree, having to load `Inject, PLATFORM_ID, isPlatformBrowser` is just adding additional code for users that don't use Universal.
Also, this isn't the only approach you can take. I use universal a lot and I would actually create a mock service and use that one in the server.module and the real one in the browser.module. 

I believe the library should only import code it always uses and leave configurations like this to the end user. What do you think?

**Comment by anode7** [comment]
Personally, I don't have a problem with that.
Maybe you should specify a method to be used in Readme?
Anyway, thank you for your work.

**Comment by flauc** [comment]
Yes you are right, will try to add that this weekend 👍
