### ISSUE TITLE
You should consider switching your application to a secure origin, such as HTTPS.

### ISSUE THREAD

**Issue by vmagalhaes** [flauc/ng-push#6]
Hi,

When I'm opening my app, it doesn't display the request permission to show the notification push, this error occur: [Deprecation] The Notification API may no longer be used from insecure origins. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

What's can be?

Thanks,

Best Regards,

**Comment by flauc** [comment]
Hi @vmagalhaes,

Well, you need to do exactly that. This has nothing to do with the library, you need to update your server.
