### ISSUE TITLE
how can I open navigator when press in notification?

### ISSUE THREAD

**Issue by LuisBonsembiante** [flauc/ng-push#7]
Thank for advance, can I open my navigator when I presed in the notificartion?
Regards

**Comment by flauc** [comment]
Hi @LuisBonsembiante 

You can listen for the click event like this 

```
this._pushNotifications.create(
    'Example One',
    {body: 'Just an example'}
)
    .subscribe(res => {
        if (res.event.type === 'click') {
            // You can do anything else here
        }
    }
)
```

**Comment by LuisBonsembiante** [comment]
thanks ready

**Comment by cedricve** [comment]
hey guys,  how is it possible to open the navigator? I see the click handler is there.
