### ISSUE TITLE
 Notifications are not displayed on mobile devices

### ISSUE THREAD

**Issue by FedeMadoery** [flauc/ng-push#8]
I use my Angular application from phones, Android or IOS and notifications are not shown. It is worth clarifying that if you ask for the permits.

Is it a kind of bug? Or is it not implemented for phones?

**Comment by LuisBonsembiante** [comment]
the same happen to me!

**Comment by anode7** [comment]
you need a service-worker to use mobile notifications

[A complete guide here, test it on mobile and PC : Notification Generator Curated by Peter Beverloo](https://tests.peter.sh/notification-generator/)

**Comment by LuisBonsembiante** [comment]
@anode7 could you send us the guide please?, the link just redirect to an example.
thanks

**Comment by anode7** [comment]
@LuisBonsembiante here's how to get started :
[Service Workers: an Introduction](https://developers.google.com/web/fundamentals/primers/service-workers/)
[Web Push Notifications: Timely, Relevant, and Precise](https://developers.google.com/web/fundamentals/push-notifications/)

**Comment by LuisBonsembiante** [comment]
@anode7 ok thanks, but we implement services working and the lib did not work.

**Comment by anode7** [comment]
@LuisBonsembiante @FedeMadoery 
A simple example using service-worker notifications. Create with "angular-cli" 1.6 : [swnotification](https://lab.digitalatelier.fr/push/)
create your swApp
`ng new swApp --service-worker
`
app.component.ts :
```
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  constructor() {
    Notification.requestPermission();
  }
  title = 'app';
  testNotif() {
    navigator.serviceWorker.ready.then(function(serviceWorker) {
      serviceWorker.showNotification("Test", { body: 'Welcome to app!' });
    })
  }

}
```
`ng build --prod`  and run on https server or localhost

**Comment by flauc** [comment]
Thank you for jumping in on this @anode7

**Comment by LuisBonsembiante** [comment]
thanks guys you are rock!
